### ISSUE TITLE
Drop serialisation and arraymorph features (being implemented in NeuroMLlite)

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#111]
Could we drop serialization and the arraymorph related features from libNeuroML? Some of this is being implemented in NeuroMLlite already, and it does not seem to be used much in libNeuroML.

**Comment by apdavison** [comment]
I've been using it in the PyNN mc branch. If you wish I could copy that code into PyNN.

**Comment by sanjayankur31** [comment]
Which bits are being used there? The json serialisation or arraymorph (or both)?

With the json serialisation, we're seeing some issues with pickling after regenerating nml.py with the newest generateDS. Please see #110. Unfortunately, I'm not sure if we can fix/workaround the issue easily enough yet.

**Comment by apdavison** [comment]
arraymorph

**Comment by pgleeson** [comment]
No, arraymorph isn't used in NeuroMLlite or elsewhere I'm aware of. Probably fine to leave these in, make sure there's just a simple test example that works with each, and de-emphasise them in the docs, maybe even explicitly state that they're not well supported.

**Comment by sanjayankur31** [comment]
Sounds good. I'll keep that bit and drop the json bits, and make a note in the docs etc.
