### ISSUE TITLE
[Bug] Errors aren't raised on parsing non-NeuroML files

### ISSUE THREAD

**Issue by jonrkarr** [NeuralEnsemble/libNeuroML#113]
**Describe the bug**
No errors are raised on the validation of non-NeuroML files

**To Reproduce**
```python
from neuroml.loaders import NeuroMLLoader
NeuroMLLoader.load(`path/to/other/file`)
```

**Expected behavior**
Raise an error

**Observed behavior**
No indication that file couldn't be parsed

**System information:**
 - OS: [e.g. iOS]: Ubuntu
 - Python version (`python --version`): 3.9.5
 - Version of tools in use (Output of `python -c 'import neuroml; print(neuroml.__version__)'`): 0.2.55

**Additional context**

**Comment by jonrkarr** [comment]
I used an SBML file such as [this](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-Fehlberg/BIOMD0000000297_url.xml).

NeuroML validation will be deployed online, alongside validation of several other model languages, very shortly at https://run.biosimulations.org/utils/validate-model (this is the development version https://run.biosimulations.dev/utils/validate-model). Currently, this uses pyneuroml which raises errors, albeit with more cryptic messages due to wrapping the underlying Java program.

**Comment by sanjayankur31** [comment]
I've added that now (please see the PR). I'll let Padraig review it since I'm not sure if there's a scenario where a valid NeuroML file would not be enclosed in a `<neuroml>` tag. (I don't think so)
