### ISSUE TITLE
[Bug] Outdated/unused dependencies (pymongo, simplejson)? 

### ISSUE THREAD

**Issue by mstimberg** [NeuralEnsemble/libNeuroML#121]
A user noted that the `libneuroml` conda package fails to install on Python 3.10, and the reason seems to be that it depends on `pymongo`, which does not provide a Python 3.10 package at the moment.
I tried to find out what `libneuroml` uses `pymongo` for, but it seems that loading JSON files from a MongoDB was removed in 44c00c2aa7db, so I guess the dependency can be removed? I did not find any mentions of `pymongo` in the code besides in the requirements. AFAICT, this commit also removed the only usage of`simplejson`, which is still listed in the `[full]` dependencies in `setup.py` (but this is less problematic since it is a pure Python dependency).

**Comment by sanjayankur31** [comment]
Fixed in development. Is this severe enough an issue to warrant a minor release (to get the conda builds to work etc.)?

**Comment by mstimberg** [comment]
I don't have a strong opinion on this (and of course it's not for me to decide), but I guess a patch level release would be the most appropriate? https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by sanjayankur31** [comment]
Sure, @pgleeson : since you're doing the releases: would a patch level release of libNeuroML be doable just to let the conda etc. bits work for py3.10?

(NEURON doesn't currently provide a pypi release for 3.10 either, so I don't think all our tests are run on 3.10 yet).
