### ISSUE TITLE
Simplification of "add" methods

### ISSUE THREAD

**Issue by apdavison** [NeuralEnsemble/libNeuroML#20]
Most of the classes have a long list of "add_this()", "add_that()" methods. Since Python makes introspection very easy, couldn't we replace all of these with a single "add()" method per class, which would do the right thing based on the object type?

This would greatly simplify the API and make it easier for users.

For example:

```
doc = NeuroMLDocument(id="my_doc")
net = Network(id="my_net")
doc.add(net)   # instead of doc.add_network(net)
pop = Population(...)
net.add(pop)   # instead of net.add_population(pop)
```

**Comment by pgleeson** [comment]
Functionality like this is best added in the [helper_methods.py](https://github.com/NeuralEnsemble/libNeuroML/blob/development/neuroml/nml/helper_methods.py). Should be straightforward to add it to the core classes there, and so enable @apdavison's suggestion in the first comment

Adding "Help required" label for anyone interisted in contributing...
