### ISSUE TITLE
Make generated API Python 3 compatible

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/libNeuroML#58]
A change is required to [generateDS.py](http://www.davekuhlman.org/generateDS.html)  for this.

@rgerkin is working on this here: https://bitbucket.org/dkuhlman/generateds/pull-request/13/changes-for-python-3-compatibility/diff

**Comment by rgerkin** [comment]
That pull request has been merged so in principle it ought to work now.  Note that you still have to run generateDS in python 2, but the generated code should work in python 3 (assuming I caught all the incompatibilities).

**Comment by pgleeson** [comment]
Thanks again @rgerkin for doing that. The latest commit (211d5c32f57776c311e261dc6c324ea9b8347721) on the development branch uses a nml.py generated from the current generateDS.py. It works fine in python2, but there are still some problems in p3:

- There are some uses of basestring, e.g. `isinstance(inStr, basestring)`. These can be converted to `isinstance(inStr, str)`

- A more serious issue is that some (not all) attributes/text contents are written to XML as bytes objects (http://www.pythoncentral.io/encoding-and-decoding-strings-in-python-3-x/) by python 3, e.g.

        <notes>b'This is an example voltage-gated Na channel'</notes>

This format is the default output for conversion of a bytes object to a string, but a better string can be generated with:

    str(my_byte_object.decode('ascii'))

though there may be an easier way to do this... Not sure if you feel like delving back into generateDS.py to look at these...

**Comment by rgerkin** [comment]
What about just running 2to3 -w on the auto-generated nml.py?  I'm already doing that, but can it be added to the function that generates it?

**Comment by rgerkin** [comment]
@pgleeson Bump

**Comment by rgerkin** [comment]
@pgleeson FYI my pull request to generateds was merged a while back

**Comment by pgleeson** [comment]
The latest code on the development branch has had 2to3 run on it. It installs correctly with python3. Some of the examples work some don't. It's mainly down to the issue mentioned above with byte objects...

**Comment by rgerkin** [comment]
@pgleeson In running the tests, several packages are required that are not listed in `install_requires` in setup.py: `tables`, `pymongo`, and `jsonpickle`.  Should I add these to setup.py?  I don't know if they are required only in the tests are are used various in libNeuroML itself.

**Comment by rgerkin** [comment]
@pgleeson They are in the travis file but not in setup.py, so a regular person installing them would get the errors until they manually installed them.

**Comment by rgerkin** [comment]
@pgleeson Also, could you give a more concrete example of a place where `nml.py` is creating a bytes object?  Then I should be able to identify the basic pattern for when this occurs, and find the corresponding places in generateDS.py where this should be fixed.  

Alternatively, I could patch jsonpickle to check for bytes objects and convert them to strings.

**Comment by rgerkin** [comment]
@pgleeson The `jsonpickle` developers actually already wrote this patch a few months ago.  That takes care of most encoding issues.  There is one remaining decoding issue related to Python 2 `__builtin__` vs Python 3 `builtins` but once I fix that all the nose tests should run in Python 3.

**Comment by pgleeson** [comment]
@rgerkin Feel free to update setup.py to require and install jsonpickle etc. It has not had a good overhaul in a while (neither has .travis.yml). Many of the issues requiring specific versions in .travis.yml could be solved now. Thanks.

**Comment by pgleeson** [comment]
Working now with PR from @clbarnes. Also being tested on Travis.
