### ISSUE TITLE
GateHHRates generates invalid NeuroML

### ISSUE THREAD

**Issue by bmerrison** [NeuralEnsemble/libNeuroML#60]
I'm afraid I'm not sure if this is a bug in libNeuroML or jNeuroML, but I suspect the former. It appears to be something that broke recently.

My code to build NeuroML models originally created gates in the following way:

``` python
        gate_ml = neuroml.GateHHRates(id="gate_{0}_{1}".format(channel.name, gate.name),
                                      type="gateHHrates",
                                      instances = gate.power,
                                      forward_rate = fwd_rate,
                                      reverse_rate = rev_rate)
```

However, I've recently switched to a new PC and in the process have updated to the latest (development) branch of libNeuroML (neuroml.__version__ is 0.2.4). With this, I get the following exception when trying to construct a GateHHRates:

```
Traceback (most recent call last):
  File "neuroml_convert.py", line 331, in <module>
    "test")
  File "neuroml_convert.py", line 191, in convert_simulation
    cell_type_ml,cell_type_ml_path = load_convert_save_cell_type(type_path)
  File "neuroml_convert.py", line 155, in load_convert_save_cell_type
    cell_type_ml, channels_ml = convert_cell_type(cell_type)
  File "neuroml_convert.py", line 117, in convert_cell_type
    channel_ml, density_ml = convert_channel(c, prefix=cell.id+"_")
  File "neuroml_convert.py", line 55, in convert_channel
    reverse_rate = rev_rate)
TypeError: __init__() got an unexpected keyword argument 'type'
```

So I removed the type="gateHHrates" line (it seemed odd that it was needed in the first place), which works and generates the following NeuroML:

``` xml
        <gate id="gate_kSlow_ks" instances="1">
            <forwardRate midpoint="2.96mV" rate="0.2per_ms" scale="7.74mV" type="HHSigmoidRate"/>
            <reverseRate midpoint="14.07mV" rate="0.05per_ms" scale="-6.1mV" type="HHSigmoidRate"/>
        </gate>
```

However, when I now try to convert the generated NeuroML into a NEURON model using jNeuroML, I get an error that "gate" is an unknown element type. Manually changing the element type in the NeuroML file to "gateHHrates" fixes the problem. My jNeuroML versions:

```
 jNeuroML v0.7.0
    org.neuroml.import  v1.4.1
    org.neuroml.export  v1.4.1
    org.neuroml.model   v1.4.1
    jLEMS               v0.9.7.3
```

Again, I'm not sure if the problem is that libNeuroML generates invalid NeuroML, or that jNeuroML thinks valid NeuroML is invalid. Apologies if this is posted to the wrong repository!

**Comment by pgleeson** [comment]
No, it's probably the right place to post it...

Yes, there have been some changes recently in [the schema](https://github.com/NeuroML/NeuroML2/blob/development/Schemas/NeuroML2/NeuroML_v2beta4.xsd) to avoid having a type attribute in an already typed element like `<gateHHrates>`. No type should be put in the constructor of GateHHRates, though it should generate an element `<gateHHrates>` not `<gate>`.

[This example](https://github.com/NeuralEnsemble/libNeuroML/blob/development/neuroml/examples/ion_channel_generation.py) has been updated to use the new form. Does it work for you?

**Comment by pgleeson** [comment]
@bmerrison ok to close this?

**Comment by sanjayankur31** [comment]
Closing this, please re-open if necessary.
