### ISSUE TITLE
Timeline for development branch merge

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/libNeuroML#61]
What is the timeline for the development branch (which is required for pyNeuromL) to be merged into master and get a PyPI release?

**Comment by pgleeson** [comment]
Not soon I'm afraid... The NeuroML 2 repos are only merged to master when there is a full beta release (incl schema, Java APIs etc.), next one is for NML v2beta4, in hopefully 3 months (but that's what I would probably have said 3 months ago...).

**Comment by pgleeson** [comment]
@rgerkin, soon, very soon...

**Comment by pgleeson** [comment]
@rgerkin the development version has been merged to master at the NML v2beta4 release, and the latest stable version (a few commits ahead) has been released to pip. 

This does create a bit of a discrepancy, but it's in line with the other NML2 repos where there is a distinction between the development and master codebases (that developers may want to contribute to; merges take place at major NML2 releases) and the latest stable binary releases (e.g. of jNeuroML) which most people will want; they just want the latest most well tested version.
