### ISSUE TITLE
No doc attribute for pulseGeneratorDL

### ISSUE THREAD

**Issue by rgerkin** [NeuralEnsemble/libNeuroML#62]
The dimensionless pulse generator `pulseGeneratorDL` cannot be located in the usual way:  

```
doc = loaders.NeuroMLLoader.load(NML_MODEL_PATH)
my_pgdls = doc.pulse_generator_dls
```
There is no such attribute in the loaded doc, only one for regular pulse_generators.  It appears that the loader does not yet match the schema in this regard.  I figure these attributes are auto-generated from some list, and since nml.py is in turn generated from generateDS.py, I figure it is best if I stay out of this one.

**Comment by pgleeson** [comment]
There's no pulseGeneratorDL in [the schema](https://github.com/NeuroML/NeuroML2/blob/development/Schemas/NeuroML2/NeuroML_v2beta4.xsd), and so none in libNeuroML.

It's reasonable to add this though, as it at least gives the ability to stimulate dimensionless cells etc. Most of the other infrastructure for dimensionless synapses/networks is not there as use of dimensional entities in NML2 is strongly encouraged. 

Will add it and let you know.

**Comment by pgleeson** [comment]
Added to the schema in the development branch: https://github.com/NeuroML/NeuroML2/blob/development/Schemas/NeuroML2/NeuroML_v2beta4.xsd#L509 & libNeuroML has been updated.
