### ISSUE TITLE
Is `neuroml/nml/nml.py` expected to be run as a script (contains shebang but is not executable)?

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#77]
Is `neuroml/nml/nml.py` meant to be run as a standalone script? It contains a shebang, but is not executable, and it's installed into `site-packages` too?

**Comment by pgleeson** [comment]
Not as far as I know. It's automatically generated by [generateDS](http://www.davekuhlman.org/generateDS.html), and I've only ever used the code as imported into a Python script with 

     import neuroml

[pynml](https://github.com/NeuroML/pyNeuroML/blob/master/pyneuroml/pynml.py) in [pyNeuroML](https://github.com/NeuroML/pyNeuroML) on the otherhand is an executable, which does lots of cool stuff like validate NML files, run in jNeuroML (the associated LEMS*.xml simulation files pointing to the NML network), convert to NEURON, pngs, svgs, PovRay, graphs, etc.

**Comment by sanjayankur31** [comment]
Thanks @pgleeson . I've opened a tiny PR to remove the shebang from this script since it isn't needed.

**Comment by pgleeson** [comment]
Thanks again for this @sanjayankur31, but I'm still not certain why this needs to be removed... The nml.py is generated automatically by generateDS.py (it loads up the  XML schema and generates a Python API from that). 

In theory nml.py can be used standalone, to try loading an XML file and will complain if it's invalid according to the schema (or more precisely if the generated parser can't handle the XML), so it's doing what it should (although we don't use the file directly that way in libNeuroML).

Removing the shebang will only require this extra step each subsequent time it's regenerated.

**Comment by sanjayankur31** [comment]
Ah, but if it is to be used as a standalone script, it should be installed in a different location (that should be in `PATH` etc.), and not in site-packages as a module file, no? I don't think users will run it as `/usr/lib/python-3.?/site-packages/neuroml/nml/nml.py ...`. If it's being installed as a module file that is only to be imported, it should not have a shebang. It can have the `if __name__ == __main__` etc bits in there for advanced users to test as `python3 ...nml.py` without needed a shebang.


This came up during the fedora package review, so it's OK to leave it in here (upstream). I can remove it in the downstream package.

**Comment by pgleeson** [comment]
It's in there because generateDS puts it there, not because libNeuroML is suggesting to users to use the file as a script. The choice to leave it there basically comes down to deciding which is more important:
- keeping the pure generateDS generated file as is so it's easier to regenerate in future
- altering the file so users (and package managers) aren't confused about why a file looks like it should be a script isn't installed as such

I can't see much reason not to go with the first option.... If you're fine to remove it manually when generating the fedora package then that would be great.

**Comment by sanjayankur31** [comment]
Sure. We'll modify it downstream. Closing the issue.

**Comment by pgleeson** [comment]
Thanks for checking anyway!
