### ISSUE TITLE
Tags to match PyPI releases

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#89]
The latest release on PyPI is 0.2.53, but the latest one on GitHub is 0.2.50. Could the missing ones please be tagged here?

(Also the latest tags are not in the master branch---are they supposed to be public releases for users?)

**Comment by pgleeson** [comment]
Making a few assorted updates/tests and hope to have a new release of all the main python packages soon and will tag/release them together...
libNeuroML is a bit of a funny one as it only goes to master when all the java libs move to master on a major (beta/2.0/2.1...) NML release...  but the latest dev is best to have as pip installable...

**Comment by sanjayankur31** [comment]
Ah, sounds good. I'll make a note of this too, so it can go into the dev docs perhaps.
