### ISSUE TITLE
RTD needs update

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#93]
The latest tagged release here is 0.2.54, but RTD still shows 0.2.18 as "latest":

https://libneuroml.readthedocs.io/en/latest/

**Comment by pgleeson** [comment]
I believe there might be some issues with the configuration at https://readthedocs.org/projects/libneuroml/ that need to be updated.

Our good colleagues @vellamike and @mattions have admin access there... Would it be possible to add me (https://readthedocs.org/profiles/pgleeson/) to the admin list there?

**Comment by mattions** [comment]
Hi @pgleeson , just added you as manteiner.

Please double check it and feel free to take it over!

Let me know if it works ok for you

**Comment by pgleeson** [comment]
@mattions That's great, thanks! 

Works fine, but now I guess we have to update the ancient documentation text...

**Comment by mattions** [comment]
Happy it works!!

Good luck on the doc update!
