### ISSUE TITLE
Could I please be added to the libNeuroML team on GitHub

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#95]
Hi @apdavison : could I please be added to the libNeuroML team on GitHub: I'm working on the NeuroML stack nowadays.

CC: @pgleeson

**Comment by apdavison** [comment]
done

**Comment by sanjayankur31** [comment]
Thanks very much! Should I be able to modify project metadata now? (labels/assignees/reviewers)? Can't seem to do that yet.

**Comment by sanjayankur31** [comment]
Ah, needed lots of refreshing :laughing: . Works now. Thanks again.

**Comment by apdavison** [comment]
while updating the team, I removed @mattions @vellamike @unidesigner from the libNeuroML team, since my understanding is that you're no longer active in the project. Please let me know if I should add you back again.

**Comment by unidesigner** [comment]
Fine with me to be removed! Greetings from Switzerland!

**Comment by vellamike** [comment]
No worries!

**Comment by mattions** [comment]
So long and thanks for all the fish!

**Comment by pgleeson** [comment]
Thanks again for your contributions to libNeuroML @mattions @vellamike @unidesigner! Feel free to jump back in any time.
