### ISSUE TITLE
Migrate off travis-ci.org

### ISSUE THREAD

**Issue by sanjayankur31** [NeuralEnsemble/libNeuroML#97]
Since travis-ci.org is going to shut down, we need to migrate off it. We could either move to travis-ci.com, or to GitHub Actions.

To move to travis-ci.com, we needn't change the travis.yml script, but it'll require some admin level changes. For GH actions, we need to just add a workflow file, like this one: https://github.com/NeuroML/pyNeuroML/blob/development/.github/workflows/ci.yml

cc: @apdavison @pgleeson

**Comment by pgleeson** [comment]
FYI @apdavison This might be a good place to start to enable use of travis-ci.com: https://travis-ci.com/organizations/NeuralEnsemble/migrate. Only admins can register an org as part of the beta for migration it seems.

I'd also like to migrate https://github.com/NeuralEnsemble/neuroConstruct...

**Comment by sanjayankur31** [comment]
I went digging to see if travis-ci.com is the right platform to migrate to. With the recent takeover of Travis, most people suggest moving off to a different system instead of moving from travis-ci.org to travis-ci.com. Apparently, in the future, Open Source repositories will need to apply for "credit" allowance on Travis, and when that runs out, apply again:

[The Travis CI Blog: The new pricing model for travis-ci.com](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) says:

> We love our OSS teams who choose to build and test using TravisCI and we fully want to support that community. However, in recent months we have encountered significant abuse of the intention of this offering (increased activity of cryptocurrency miners, TOR nodes operators etc.). Abusers have been tying up our build queues and causing performance reductions for everyone. In order to bring the rules back to fair playing grounds, we are implementing some changes for our public build repositories.
> 
> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
> You will not need to change your build definitions when you are pointed to the new plan
> When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
> - We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. 
> -  Please include:
> - - Your account name and VCS provider (like travis-ci.com/github/[your account name] )
> - - How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)
> - - Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used
> 

So, it's not looking like a good long term plan to migrate to travis-ci.com. It looks like GH Actions is the preferred replacement: it also gets rid of the administration that third party CI services require. GitLab CI seems to be the ideal candidate but for those with lots of repos on GitHub migrating will require quite a bit of work---which is perhaps overkill at the moment.

- [rOpenSci | Moving away from Travis CI](https://ropensci.org/blog/2020/11/19/moving-away-travis/)
- Discussion around the post: [Moving Away from Travis CI | Hacker News](https://news.ycombinator.com/item?id=25155203)
- More info on layoffs at Travis: [Travis CI Is Laying Off Senior Engineer Staff | Hacker News](https://news.ycombinator.com/item?id=19218036)

**Comment by sanjayankur31** [comment]
I've added the GH workflow to the development branch now. If we do decide to migrate from travis-ci.org to travis-ci.com, that can be removed easilly.

You can see the workflow here: https://github.com/NeuralEnsemble/libNeuroML/actions

**Comment by sanjayankur31** [comment]
(it's currently failing because of the flake errors noted in #99  which are addressed in #98 )
